"use client";

import { useEffect, useState, useRef, useCallback } from "react";
import { usePopoverContext } from "@/contexts/PopoverContext";
import { findConceptByTerm, findConceptById } from "@/lib/concept-graph";
import type { GraphConcept } from "@/lib/types-graph";

interface ConceptData {
  term: string;
  onSearch: (query: string) => void;
}

export default function GlobalPopover() {
  const { openPopover, close, setHoveringPopover } = usePopoverContext();
  const [style, setStyle] = useState<React.CSSProperties>({});
  const popoverRef = useRef<HTMLDivElement>(null);

  const handleMouseEnter = useCallback(() => {
    setHoveringPopover(true);
  }, [setHoveringPopover]);

  const handleMouseLeave = useCallback(() => {
    setHoveringPopover(false);
  }, [setHoveringPopover]);

  // Calculate position when popover opens
  useEffect(() => {
    if (!openPopover) return;

    const rect = openPopover.triggerRect;
    const popoverWidth = Math.min(280, window.innerWidth * 0.9);
    const popoverHeight = 200;
    const gap = 8;

    const spaceBelow = window.innerHeight - rect.bottom;
    const spaceAbove = rect.top;
    const showAbove = spaceBelow < popoverHeight + gap && spaceAbove > spaceBelow;

    let left = rect.left + rect.width / 2 - popoverWidth / 2;
    left = Math.max(10, Math.min(left, window.innerWidth - popoverWidth - 10));

    const newStyle: React.CSSProperties = {
      position: 'fixed',
      left: `${left}px`,
      width: `${popoverWidth}px`,
      zIndex: 100,
    };

    if (showAbove) {
      newStyle.bottom = `${window.innerHeight - rect.top + gap}px`;
    } else {
      newStyle.top = `${rect.bottom + gap}px`;
    }

    setStyle(newStyle);
  }, [openPopover]);

  // Close on click outside
  useEffect(() => {
    if (!openPopover) return;

    const handleClickOutside = (e: MouseEvent) => {
      if (popoverRef.current && !popoverRef.current.contains(e.target as Node)) {
        close();
      }
    };

    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === "Escape") close();
    };

    // Small delay to prevent immediate close from the opening click
    const timer = setTimeout(() => {
      document.addEventListener("mousedown", handleClickOutside);
      document.addEventListener("keydown", handleEscape);
    }, 10);

    return () => {
      clearTimeout(timer);
      document.removeEventListener("mousedown", handleClickOutside);
      document.removeEventListener("keydown", handleEscape);
    };
  }, [openPopover, close]);

  if (!openPopover) return null;

  // Handle AI Companion Badge popover
  if (openPopover.id === "ai-companion-badge") {
    return (
      <div
        ref={popoverRef}
        role="dialog"
        aria-label="About AI Companion"
        className="concept-popover"
        style={style}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        <div className="concept-popover-content">
          <p className="text-sm text-[var(--lo1-text-light)] leading-relaxed">
            This response was generated by an AI trained to help explore the
            Ra Material. While it searches authentic quotes and attempts to be
            accurate, it may occasionally misunderstand or oversimplify
            complex concepts.
          </p>
          <p className="text-xs text-[var(--lo1-stardust)] mt-3 italic">
            Always verify important insights against the original material.
          </p>
        </div>
      </div>
    );
  }

  // Handle Concept popovers
  if (openPopover.id.startsWith("concept-")) {
    const data = openPopover.data as ConceptData | undefined;
    if (!data) return null;

    const concept = findConceptByTerm(data.term);
    const definition = concept?.definition;

    const relatedConcepts = concept?.relationships.related
      ?.slice(0, 3)
      .map(id => findConceptById(id))
      .filter((c): c is GraphConcept => c !== undefined)
      .map(c => c.term) || [];

    const keySessions = concept?.sessions.primary.slice(0, 3) || [];

    const handleSearch = (e: React.MouseEvent) => {
      e.preventDefault();
      e.stopPropagation();
      close();
      data.onSearch(`Please help me understand ${data.term}`);
    };

    return (
      <div
        ref={popoverRef}
        role="dialog"
        aria-label={`Definition of ${data.term}`}
        className="concept-popover"
        style={style}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      >
        <span className="concept-popover-content">
          <span className="concept-popover-header">
            <span className="concept-popover-term">{concept?.term || data.term}</span>
            {concept?.category && (
              <span className="concept-popover-category">{concept.category}</span>
            )}
          </span>
          {definition && <span className="concept-popover-definition">{definition}</span>}
          {relatedConcepts.length > 0 && (
            <span className="concept-popover-related">
              <span className="concept-popover-related-label">Related:</span>
              <span className="concept-popover-related-terms">
                {relatedConcepts.join(", ")}
              </span>
            </span>
          )}
          {keySessions.length > 0 && (
            <span className="concept-popover-sessions">
              <span className="concept-popover-sessions-label">Key sessions:</span>
              <span className="concept-popover-sessions-list">
                {keySessions.map((s, i) => (
                  <a
                    key={s}
                    href={`https://lawofone.info/s/${s}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="concept-popover-session-link"
                    onClick={(e) => e.stopPropagation()}
                  >
                    {s}{i < keySessions.length - 1 ? ", " : ""}
                  </a>
                ))}
              </span>
            </span>
          )}
          <button onClick={handleSearch} className="concept-popover-search-btn">
            Explore this concept
          </button>
        </span>
      </div>
    );
  }

  return null;
}
